todosrht/urls.py
from flask import has_app_context, url_for
from jinja2.utils import url_quote
from todosrht.types import ParticipantType

def tracker_url(tracker):
    return url_for("tracker.tracker_GET",
        owner=tracker.owner.canonical_name,
        name=tracker.name)

def tracker_labels_url(tracker):
    return url_for("tracker.tracker_labels_GET",
        owner=tracker.owner.canonical_name,
        name=tracker.name)

def ticket_url(ticket, event=None):
    if has_app_context():
        ticket_url = url_for("ticket.ticket_GET",
                owner=ticket.tracker.owner.canonical_name,
                name=ticket.tracker.name,
                ticket_id=ticket.scoped_id)
    else:
        ticket_url = (f"/{ticket.tracker.owner.canonical_name}" +
            f"/{ticket.tracker.name}" +
            f"/{ticket.scoped_id}")

    if event:
        ticket_url += "#event-" + str(event.id)

    return ticket_url

def ticket_edit_url(ticket):
    return url_for("ticket.ticket_edit_GET",
        owner=ticket.tracker.owner.canonical_name,
        name=ticket.tracker.name,
        ticket_id=ticket.scoped_id)

def ticket_delete_url(ticket):
    return url_for("ticket.ticket_delete_GET",
        owner=ticket.tracker.owner.canonical_name,
        name=ticket.tracker.name,
        ticket_id=ticket.scoped_id)

def ticket_assign_url(ticket):
    return url_for("ticket.ticket_assign",
        owner=ticket.tracker.owner.canonical_name,
        name=ticket.tracker.name,
        ticket_id=ticket.scoped_id)

def ticket_unassign_url(ticket):
    return url_for("ticket.ticket_unassign",
        owner=ticket.tracker.owner.canonical_name,
        name=ticket.tracker.name,
        ticket_id=ticket.scoped_id)

def label_edit_url(label):
    return url_for("tracker.label_edit_GET",
        owner=label.tracker.owner.canonical_name,
        name=label.tracker.name,
        label_name=label.name)

def label_search_url(label, terms=""):
    """Return the URL to the tracker page listing all tickets which have the
    label applied."""
    label_term = f"label:\"{label.name}\""
    if not terms:
        terms = label_term
    elif label_term not in terms:
        terms += " " + label_term
    return "{}?search={}".format(
        tracker_url(label.tracker),
        url_quote(terms))

def label_add_url(ticket):
    """Return the URL to add a label to a ticket."""
    return url_for("ticket.ticket_add_label",
            owner=ticket.tracker.owner.canonical_name,
            name=ticket.tracker.name,
            ticket_id=ticket.scoped_id)

def label_remove_url(label, ticket):
    """Return the URL to remove a label from a ticket."""
    return url_for("ticket.ticket_remove_label",
            owner=ticket.tracker.owner.canonical_name,
            name=ticket.tracker.name,
            ticket_id=ticket.scoped_id,
            label_id=label.id)

def participant_url(participant):
    if participant.participant_type == ParticipantType.user:
        return url_for("html.user_GET", username=participant.user.username)
    elif participant.participant_type == ParticipantType.email:
        if participant.email_name:
            return f"mailto:{participant.email_name} <{participant.email}>"
        else:
            return f"mailto:{participant.email}"
    elif participant.participant_type == ParticipantType.external:
        return participant.external_url

def user_url(user):
    return url_for("html.user_GET", username=user.username)

todosrht/blueprints/settings.py
import gzip
import json
import os
from collections import OrderedDict
from flask import Blueprint, current_app, render_template, request, url_for, abort, redirect
from flask import current_app, send_file
from srht.config import get_origin
from srht.crypto import sign_payload
from srht.database import db
from srht.oauth import current_user, loginrequired
from srht.flask import date_handler, session
from srht.graphql import exec_gql, GraphQLOperation, GraphQLUpload
from srht.validation import Validation
from tempfile import NamedTemporaryFile
from todosrht.access import get_tracker
from todosrht.trackers import get_recent_users
from todosrht.types import Event, EventType, Ticket, TicketAccess, Visibility
from todosrht.types import ParticipantType, UserAccess, User
from todosrht.urls import tracker_url

settings = Blueprint("settings", __name__)

def parse_html_perms(short, valid):
    result = 0
    for sub_perm in TicketAccess:
        new_perm = valid.optional("perm_{}_{}".format(short, sub_perm.name))
        if new_perm:
            result |= int(new_perm)
    return result

access_help_map={
    TicketAccess.browse:
        "Permission to view tickets",
    TicketAccess.submit:
        "Permission to submit tickets",
    TicketAccess.comment:
        "Permission to comment on tickets",
    TicketAccess.edit:
        "Permission to edit tickets",
    TicketAccess.triage:
        "Permission to resolve, re-open, or label tickets",
}

@settings.route("/<owner>/<name>/settings/details")
@loginrequired
def details_GET(owner, name):
    tracker, access = get_tracker(owner, name)
    if not tracker:
        abort(404)
    if current_user.id != tracker.owner_id:
        abort(403)
    return render_template("tracker-details.html",
        view="details", tracker=tracker)

@settings.route("/<owner>/<name>/settings/details", methods=["POST"])
@loginrequired
def details_POST(owner, name):
    tracker, access = get_tracker(owner, name)
    if not tracker:
        abort(404)
    if current_user.id != tracker.owner_id:
        abort(403)

    valid = Validation(request)
    input = {
        key: valid.source[key] for key in [
            "description", "visibility",
        ] if valid.source.get(key) is not None
    }

    resp = exec_gql(current_app.site, """
        mutation UpdateTracker($id: Int!, $input: TrackerInput!) {
            updateTracker(id: $id, input: $input) {
                name
                owner {
                    canonicalName
                }
            }
        }
    """, valid=valid, id=tracker.id, input=input)

    if not valid.ok:
        return render_template("tracker-details.html",
            tracker=tracker, **valid.kwargs), 400

    resp = resp["updateTracker"]

    return redirect(url_for("settings.details_GET",
        owner=resp["owner"]["canonicalName"],
        name=resp["name"]))


def render_tracker_access(tracker, **kwargs):
    recent_users = get_recent_users(tracker)
    return render_template("tracker-access.html",
        view="access", tracker=tracker, access_type_list=TicketAccess,
        access_help_map=access_help_map, recent_users=recent_users, **kwargs)


@settings.route("/<owner>/<name>/settings/access")
@loginrequired
def access_GET(owner, name):
    tracker, access = get_tracker(owner, name)
    if not tracker:
        abort(404)
    if current_user.id != tracker.owner_id:
        abort(403)
    return render_tracker_access(tracker)

@settings.route("/<owner>/<name>/settings/access", methods=["POST"])
@loginrequired
def access_POST(owner, name):
    tracker, access = get_tracker(owner, name)
    if not tracker:
        abort(404)
    if current_user.id != tracker.owner_id:
        abort(403)

    valid = Validation(request)
    access = parse_html_perms('default', valid)
    input = {
        perm: ((access & TicketAccess[perm].value) != 0) for perm in [
            "browse", "submit", "comment", "edit", "triage",
        ]
    }

    resp = exec_gql(current_app.site, """
        mutation updateTrackerACL($id: Int!, $input: ACLInput!) {
            updateTrackerACL(trackerId: $id, input: $input) {
                browse
            }
        }
    """, valid=valid, id=tracker.id, input=input)

    if not valid.ok:
        return render_tracker_access(tracker, **valid.kwargs), 400

    return redirect(tracker_url(tracker))

@settings.route("/<owner>/<name>/settings/user-access/create", methods=["POST"])
@loginrequired
def user_access_create_POST(owner, name):
    tracker, access = get_tracker(owner, name)
    if not tracker:
        abort(404)
    if current_user.id != tracker.owner_id:
        abort(403)

    valid = Validation(request)
    username = valid.require("username")
    permissions = parse_html_perms("user_access", valid)
    if not valid.ok:
        return render_tracker_access(tracker, **valid.kwargs), 400

    username = username.lstrip("~")
    user = current_app.oauth_service.lookup_user(username)
    valid.expect(user, "User not found.", field="username")
    if not valid.ok:
        return render_tracker_access(tracker, **valid.kwargs), 400

    existing = UserAccess.query.filter_by(user=user, tracker=tracker).count()

    valid.expect(user != tracker.owner,
        "Cannot override tracker owner's permissions.", field="username")
    valid.expect(existing == 0,
        "This user already has custom permissions assigned.", field="username")
    if not valid.ok:
        return render_tracker_access(tracker, **valid.kwargs), 400

    ua = UserAccess(tracker=tracker, user=user, permissions=permissions)
    db.session.add(ua)
    db.session.commit()

    return redirect(url_for("settings.access_GET",
            owner=tracker.owner.canonical_name,
            name=name))

@settings.route("/<owner>/<name>/settings/user-access/<user_id>/delete",
    methods=["POST"])
@loginrequired
def user_access_delete_POST(owner, name, user_id):
    tracker, access = get_tracker(owner, name)
    if not tracker:
        abort(404)
    if current_user.id != tracker.owner_id:
        abort(403)

    UserAccess.query.filter_by(user_id=user_id, tracker_id=tracker.id).delete()
    db.session.commit()

    return redirect(url_for("settings.access_GET",
            owner=tracker.owner.canonical_name,
            name=name))

@settings.route("/<owner>/<name>/settings/delete")
@loginrequired
def delete_GET(owner, name):
    tracker, access = get_tracker(owner, name)
    if not tracker:
        abort(404)
    if current_user.id != tracker.owner_id:
        abort(403)
    return render_template("tracker-delete.html",
        view="delete", tracker=tracker)

@settings.route("/<owner>/<name>/settings/delete", methods=["POST"])
@loginrequired
def delete_POST(owner, name):
    tracker, access = get_tracker(owner, name)
    if not tracker:
        abort(404)
    if current_user.id != tracker.owner_id:
        abort(403)

    exec_gql(current_app.site, """
    mutation DeleteTracker($id: Int!) {
        deleteTracker(id: $id) { id }
    }
    """, id=tracker.id);

    session["notice"] = f"{tracker.owner}/{tracker.name} was deleted."
    return redirect(url_for("html.index_GET"))

@settings.route("/<owner>/<name>/settings/import-export")
@loginrequired
def import_export_GET(owner, name):
    tracker, access = get_tracker(owner, name)
    if not tracker:
        abort(404)
    if current_user.id != tracker.owner_id:
        abort(403)
    return render_template("tracker-import-export.html",
        view="import/export", tracker=tracker)

@settings.route("/<owner>/<name>/settings/export", methods=["POST"])
@loginrequired
def export_POST(owner, name):
    tracker, access = get_tracker(owner, name)
    if not tracker:
        abort(404)
    if current_user.id != tracker.owner_id:
        abort(403)

    upstream = get_origin("todo.sr.ht", external=True)

    def participant_to_dict(self):
        if self.participant_type == ParticipantType.user:
            return {
                "type": "user",
                "user_id": self.user.id,
                "canonical_name": self.user.canonical_name,
                "name": self.user.username,
            }
        elif self.participant_type == ParticipantType.email:
            return {
                "type": "email",
                "address": self.email,
                "name": self.email_name,
            }
        elif self.participant_type == ParticipantType.external:
            return {
                "type": "external",
                "external_id": self.external_id,
                "external_url": self.external_url,
            }
        assert False

    dump = list()
    tickets = Ticket.query.filter(Ticket.tracker_id == tracker.id).all()
    for ticket in tickets:
        td = {
            "id": ticket.scoped_id,
            "created": ticket.created,
            "updated": ticket.updated,
            "submitter": participant_to_dict(ticket.submitter),
            "ref": ticket.ref(),
            "subject": ticket.title,
            "body": ticket.description,
            "status": ticket.status.name.upper(),
            "resolution": ticket.resolution.name.upper(),
            "labels": [l.name for l in ticket.labels],
            "assignees": [u.to_dict(short=True) for u in ticket.assigned_users],
        }
        td["upstream"] = upstream
        if ticket.submitter.participant_type == ParticipantType.user:
            sigdata = OrderedDict({
                "tracker_id": tracker.id,
                "ticket_id": ticket.scoped_id,
                "subject": ticket.title,
                "body": ticket.description,
                "submitter_id": ticket.submitter.user.id,
                "upstream": upstream,
            })
            sigdata = json.dumps(sigdata, separators=(',',':'))
            signature = sign_payload(sigdata)
            td.update(signature)

        events = Event.query.filter(Event.ticket_id == ticket.id).all()
        if any(events):
            td["events"] = list()

todosrht/templates/edit-comment.html
{% extends "layout.html" %}
{% block title %}
<title>
  {{ ticket.ref() }}: {{ ticket.title }}
  &mdash;
  {{ cfg("sr.ht", "site-name") }} todo
</title>
{% endblock %}
{% block body %}
<div class="container">
  <h2 class="ticket-title">
    <div>
      <a href="{{ tracker.owner|user_url }}"
        >{{ tracker.owner }}</a>/<a href="{{ tracker|tracker_url }}"
        >{{ tracker.name }}</a>#{{ ticket.scoped_id }}<span
          class="d-none d-md-inline">:</span>&nbsp;
    </div>
    <div id="title-field">
      {{ticket.title}}
    </div>
  </h2>
</div>
<div class="header-tabbed">
  {% if not tracker_sub %}
  <form method="POST" action="{{url_for("ticket." +
      ("disable_notifications" if ticket_sub else "enable_notifications"),
      owner=tracker.owner.canonical_name,
      name=tracker.name,
      ticket_id=ticket.scoped_id)}}"
    class="container"
  >
    {{csrf_token()}}
  {% else %}
  <div class="container">
  {% endif %}
    <ul class="nav nav-tabs">
      <li class="nav-item">
        <a href="{{ ticket|ticket_url }}"
          class="nav-link active">view</a>
      </li>
      {% if TicketAccess.edit in access %}
      <li class="nav-item">
        <a href="{{ ticket|ticket_edit_url }}"
          class="nav-link">edit</a>
      </li>
      {% endif %}
      <li class="flex-grow-1 d-none d-md-block"></li>
      <li class="nav-item">
        {% if current_user %}
        <button
          class="nav-link active"
          {% if tracker_sub %}
          title="you are subscribed to all activity on this tracker"
          disabled
          {% else %}
          type="submit"
          {% endif %}
        >
          {{icon("envelope-o")}}
          {% if ticket_sub or tracker_sub %}
          Disable notifications
          {% else %}
          Enable notifications
          {% endif %}
          {{icon("caret-right")}}
        </button>
        {% else %}
        <a class="nav-link active" href="{{ ticket_subscribe }}">
          {{icon("envelope-o")}}
          Subscribe
          {{icon("caret-right")}}
        </a>
        {% endif %}
      </li>
    </ul>
  {% if not tracker_sub %}
  </form>
  {% else %}
  </div>
  {% endif %}
</div>
<div class="container">
  <div class="row">
    <div class="col-md-6">
      {% if ticket.description %}
      <div id="description-field">
        {{ ticket|render_ticket_description }}
      </div>
      {% endif %}
    </div>
    <div class="col-md-6">
      <dl class="row">
        <dt class="col-md-3">Status</dt>
        <dd class="col-md-9">
          <strong id="status-field" class="text-success">
            {{ ticket.status.name.upper() }}
            {% if ticket.status == TicketStatus.resolved %}
            {{ ticket.resolution.name.upper() }}
            {% endif %}
          </strong>
        </dd>
        <dt class="col-md-3">Submitter</dt>
        <dd class="col-md-9">
          <a
            id="submitter-field"
            href="{{ ticket.submitter|participant_url }}"
          >{{ ticket.submitter }}</a>
          {% if ticket.authenticity.name == "unauthenticated" %}
          <span
            class="text-danger"
            title="This ticket was imported from an external source and its authenticity cannot be guaranteed."
          >(unverified)</span>
          {% elif ticket.authenticity.name == "tampered" %}
          <span
            class="text-danger"
            title="This ticket has been edited by a third-party - its contents are not genuine."
          >(edited)</span>
          {% endif %}
        </dd>
        <dt class="col-md-3">Assigned to</dt>
        <dd id="assignee-field" class="col-md-9">
          {% for assignee in ticket.assigned_users %}
          <div class="row">
            <div class="col">
              <a href="{{ assignee|user_url }}">{{ assignee }}</a>
            </div>
          </div>
          {% endfor %}
          {% if not ticket.assigned_users %}
          No-one
          {% endif %}
        </dd>
        <dt class="col-md-3">Submitted</dt>
        <dd id="submitted-field" class="col-md-9">
        {{ ticket.created | date }}</dd>
        <dt class="col-md-3">Updated</dt>
        <dd id="updated-field" class="col-md-9">
        {{ ticket.updated | date }}</dd>
        <dt class="col-md-3">Labels</dt>
        <dd id="labels-field" class="col-md-9">
          {% for label in ticket.labels %}
            {{ label|label_badge }}
          {% else %}
            No labels applied.
          {% endfor %}
        </dd>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12 event-list ticket-events">
      <h3>Edit comment</h3>
      <div class="event">
        <h4>
          <a
            href="{{ comment.submitter|participant_url }}"
          >{{ comment.submitter }}</a>
          {% if comment.authenticity.name == "unauthenticated" %}
          <span
            class="text-danger"
            title="This comment was imported from an external source and its authenticity cannot be guaranteed."
          >(unverified)</span>
          {% elif comment.authenticity.name == "tampered" %}
          <span
            class="text-danger"
            title="This comment has been edited by a third-party."
          >(edited)</span>
          {% endif %}
          <span class="pull-right">
            <small>
              {{ comment.created | date }}
            </small>
          </span>
        </h4>
        <form style="margin-top: 1rem" method="POST">
          {{csrf_token()}}
          <div class="form-group">
            <textarea
              class="form-control {{valid.cls('text')}}"
              name="text"
              rows="5"
            >{{text or comment.text}}</textarea>
            {{valid.summary("text")}}
          </div>
          <button
            id="comment-submit"
            type="submit"
            class="btn btn-primary"
          >Submit {{icon("caret-right")}}</button>
          <button
            type="submit"
            name="preview"
            value="true"
            class="btn btn-default"
          >Preview {{icon("caret-right")}}</button>
        </form>
      </div>

      {% if rendered_preview %}
      <div class="event preview">
        <span class="preview-tag">Comment preview</span>
        <a href="{{ current_user|user_url }}">{{ current_user }}</a>
        <blockquote>
          {{ rendered_preview }}
        </blockquote>
      </div>
      {% endif %}
    </div>
  </div>
</div>
{% endblock %}

todosrht/templates/tracker-access.html
{% extends "settings.html" %}
{% block title %}
<title>Configure {{tracker.owner}}/{{tracker.name}} &mdash; {{ cfg("sr.ht", "site-name") }}</title>
{% endblock %}
{% macro perm_checkbox(type, perms, name, readonly=False) %}
{% if type.name not in ["none", "all"] %}
<div class="form-check form-check-inline">
  <label class="form-check-label" title="{{access_help_map[type]}}">
    {% if readonly %}
      {% if type in perms %}
        {{icon('check', cls='text-success')}}
      {% else %}
        <span style="display: inline-block; min-width: 16px;">
          {{icon('times', cls='text-danger')}}
        </span>
      {% endif %}
      {{type.name}}
    {% else %}
      {% if type %}
        <input
          class="form-check-input"
          type="checkbox"
          name="perm_{{ name }}_{{ type.name }}"
          value="{{type.value}}"
          {{ "checked" if type in perms }}> {{type.name}}
      {% else %}
        <input
          class="form-check-input"
          type="checkbox"
          name="perm_{{ name }}_{{ type.name }}"
          value="{{type.value}}"
          {{ "checked" if perms == 0 }}> {{type.name}}
      {% endif %}
    {% endif %}
  </label>
</div>
{% endif %}
{% endmacro %}
{% block content %}
<div class="row">
  <div class="col-md-12">
    <form method="POST">
      {{csrf_token()}}
      <div class="form-group {{valid.cls("tracker_default_access")}}">
        <p>
          These permissions allow you to control what kinds of users are able
          to do what sorts of activities on your tracker.
        </p>
        <div class="event-list">
          <div class="event">
            <h4>Default Permissions</h4>
            <p>
              These permissions are used for anyone who does not have a more
              specific access configuration.
            </p>
            {% for a in access_type_list %}
            {{ perm_checkbox(a, tracker.default_access, "default") }}
            {% endfor %}
            {{ valid.summary("tracker_default_access") }}
          </div>
        </div>
      </div>
      {{ valid.summary() }}
      <span class="pull-right">
        <button type="submit" class="btn btn-primary">
          Save {{icon("caret-right")}}
        </button>
      </span>
    </form>

    <div class="clearfix"></div>

    <h3>User permissions</h3>
    <form
      method="POST"
      class="form-horizontal"
      action="{{ url_for("settings.user_access_create_POST",
          owner=tracker.owner.canonical_name,
          name=tracker.name) }}"
    >
      {{ csrf_token() }}
      <div class="form-group" style="margin-top: 1rem">
        <label for="username">Username or email</label>
        <input
          type="text"
          class="form-control {{valid.cls("username")}}"
          id="username"
          name="username"
          placeholder="~{{ current_user.username }}"
          autocomplete="off"
          list="user-list"
          value="{{username or ""}}"
          required
        />
        <datalist id="user-list">
          {% for u in recent_users %}
            <option value="~{{ u }}" />
          {% endfor %}
        </datalist>
        {{ valid.summary("username") }}
      </div>

      <div class="event-list">
        <div class="event form-group">
          <h4>Permissions</h4>
          <p>
            These settings will override all permissions for a specific user.
          </p>
          {% for a in access_type_list %}
          {{ perm_checkbox(a, TicketAccess.all, "user_access") }}
          {% endfor %}
          {{ valid.summary("user_access") }}
        </div>
      </div>

      <span class="pull-right">
        <button type="submit" class="btn btn-primary">
          Add {{icon("caret-right")}}
        </button>
      </span>
    </form>

    {% if tracker.user_accesses %}
    <table class="table">
      <thead>
        <tr>
          <th>user</th>
          <th>granted</th>
          <th>access</th>
          <th style="width: 10%"></th>
        </tr>
      </thead>
      <tbody>
        {% for user_access in tracker.user_accesses %}
        <tr>
          <td>
            <a
              href="{{url_for("html.user_GET",
                username=user_access.user.username)}}"
            >~{{user_access.user.username}}</a>
          </td>
          <td>{{ user_access.created|date }}</td>
          <td>
            {% for a in access_type_list %}
            {{ perm_checkbox(a, user_access.permissions, "user", readonly=True) }}
            {% endfor %}
          </td>
          <td>
            <form
              action="{{ url_for("settings.user_access_delete_POST",
                  owner=tracker.owner.canonical_name,
                  name=tracker.name,
                  user_id=user_access.user_id) }}"
              method="POST"
              style="margin: 0"
            >
              {{ csrf_token() }}
              <button type="submit" class="btn btn-danger btn-fill">
                Delete
              </button>
            </form>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    {% endif %}
  </div>
</div>
{% endblock %}

{% block scripts %}
<script type="text/javascript">
// @license magnet:?xt=urn:btih:0b31508aeb0634b347b8270c7bee4d411b5d4109&dn=agpl-3.0.txt AGPL-3.0-only
  {% include "autocomplete.js" %}

  (function() {
    const input = document.getElementById("username");
    const list = document.getElementById("user-list");
    if (input && list) {
      autocomplete = new UserAutoComplete(input, list);
      autocomplete.register();
    }
  })();
// @license-end
</script>
{% endblock %}

todosrht/templates/tracker-delete.html
{% extends "settings.html" %}
{% block title %}
<title>Delete {{tracker.owner}}/{{tracker.name}} &mdash; {{ cfg("sr.ht", "site-name") }}</title>
{% endblock %}
{% block content %}
<div class="row">
  <div class="col-md-12">
    <p>
      This will permanently delete your tracker,
      <strong>{{ tracker.owner }}/{{ tracker.name }}</strong>, and all of
      its tickets. This cannot be undone.
    </p>
    <form method="POST">
      {{csrf_token()}}
      <button type="submit" class="btn btn-danger">
        Proceed and delete {{icon("caret-right")}}
      </button>
      <a
        href="/{{ tracker.owner }}/{{ tracker.name }}"
        class="btn btn-default"
      >Nevermind</a>
    </form>
  </div>
</div>
{% endblock %}

todosrht/templates/tracker-import-export.html
{% extends "settings.html" %}
{% block title %}
<title>Configure {{tracker.owner}}/{{tracker.name}} &mdash; {{ cfg("sr.ht", "site-name") }}</title>
{% endblock %}
{% block content %}
<div class="row">
  <div class="col-md-12">
    <form method="POST" action="{{url_for('settings.export_POST',
        owner=tracker.owner.canonical_name, name=tracker.name)}}">
      {{csrf_token()}}
      <h3>Export tracker dump</h3>
      <p>
        This tool will export a JSON dump which includes all data on this
        tracker. The export format is a single JSON file including each ticket
        and its events in the same format as provided via the
        <a href="https://man.sr.ht/todo.sr.ht/api.md">todo.sr.ht API</a>.
      </p>
      <details style="margin-bottom: 1rem">
        <summary class="text-muted">
          Some of this data is cryptographically signed.
          Expand this for details.
        </summary>
        <blockquote>
          <p>
            We provide cryptographic signatures for some ticket info and
            comment details in the exported data. This can be used if you
            re-import this dump into todo.sr.ht or into another instance
            elsewhere to prove that the data is an authentic representation of
            what each user had said.
          </p>
          <p>
            For each ticket, the signature uses the
            <a
              href="https://man.sr.ht/api-conventions.md#webhook-signatures"
            >webhook signature process</a>
            after preparing the following JSON data as UTF-8:
          </p>
<pre>{
  "tracker_id": <strong>$trackerId</strong>,
  "ticket_id": <strong>$ticketId</strong>,
  "subject": <strong>$subject</strong>,
  "body": <strong>$body</strong>,
  "submitter_id": "<strong>$userId</strong>",
  "upstream": "{{get_origin('todo.sr.ht', external=True)}}",
}</pre>
          <p>
            Comments use the same process with the following JSON data as UTF-8:
          </p>
<pre>{
  "tracker_id": <strong>$trackerId</strong>,
  "ticket_id": <strong>$ticketId</strong>,
  "comment": <strong>$comment</strong>,
  "author_id": "<strong>$userId</strong>",
  "upstream": "{{get_origin('todo.sr.ht', external=True)}}",
}</pre>
          <p>
            In each case, the resulting JSON is minified before being signed.
            Signatures are only used for tickets and comments from users with
            accounts; external users' emailed submissions are not signed.
          </p>
        </blockquote>
      </details>
      <button type="submit" class="btn btn-primary">
        Export tracker data
        {{icon('caret-right')}}
      </button>
    </form>
    <form
      method="POST"
      action="{{url_for('settings.import_POST',
        owner=tracker.owner.canonical_name, name=tracker.name)}}"
      enctype="multipart/form-data"
    >
      {{csrf_token()}}
      <h3>Import tracker dump</h3>
      <p>
        This tool will re-import a gzipped JSON dump generated by the export
        tool on this or another todo.sr.ht instance.
      </p>
      <div class="form-group">
        <input
          type="file"
          name="dump"
          class="form-control {{valid.cls('dump')}}"
          required />
        {{valid.summary("dump")}}
      </div>
      <button type="submit" class="btn btn-primary">
        Import tracker data
        {{icon('caret-right')}}
      </button>
    </form>
  </div>
</div>
{% endblock %}